package principal;

import java.util.ArrayList;
import java.util.List;

public class SQLGerado extends javax.swing.JFrame {
    private final List<List<String>> dados;
    private List<String> tabelas = new ArrayList<>();
    private List<String> atributos = new ArrayList<>();
    
    public SQLGerado(List<List<String>> dados) {
        this.dados = dados;
        initComponents();
        preencherListas();
    }
    
    private void preencherListas(){
        preencherListaTabelas();
        preencherListaAtributos();
        String sql = gerarSQL();
        taSQL.setText(sql);
    }
    
    private void preencherListaTabelas(){
        for (List<String> linha: dados) {
            if (tabelas.isEmpty()) {
                tabelas.add(linha.get(1));
            } else {
                for (String tabela: tabelas) {
                    if (!tabela.equals(linha.get(1))) {
                        tabelas.add(linha.get(1));
                        break;
                    }
                }
            }
        }
    }
    
    private void preencherListaAtributos(){
        for (List<String> linha: dados) {
            atributos.add(linha.get(2));
        }
    }
    
    private String gerarSQL(){
        String atributosLocal = "";
        for (int i = 0; i < this.atributos.size(); i++) {
            if (i == (this.atributos.size() - 1)) {
                atributosLocal = atributosLocal + this.atributos.get(i);
            } else {
                atributosLocal = atributosLocal + this.atributos.get(i) + ", ";
            }
        }
        return "SELECT " + atributosLocal + " FROM " + dados.get(0).get(0) + "." + tabelas.get(0) + ";";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taSQL = new javax.swing.JTextArea();
        lTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SQL Gerado");

        taSQL.setEditable(false);
        taSQL.setColumns(20);
        taSQL.setRows(5);
        jScrollPane1.setViewportView(taSQL);

        lTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lTitulo.setText("SELECT GERADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 571, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextArea taSQL;
    // End of variables declaration//GEN-END:variables
}